#!/bin/sh

set -e

TMP=$(getopt -o t:N:aBbcDdeFfHhIiLlOovXx -q -- "${@}")

eval set -- ${TMP}

REAL_OD=/usr/bin/od

OPTS=
INPUT_CMD=
INPUT_FILE=
while true; do
    case "$1" in
	-t)
	    case "$2" in
		"") shift 2;;
		x) OPTS="${OPTS} -X"; shift 2;;
		*) OPTS="${OPTS} -t $2"; shift 2;;
	    esac ;;
	-N)
	    case "$2" in
		"") shift 2;;
		*)
		    INPUT_CMD="dd count=1 bs=$2";
		    shift 2;;
	    esac ;;
	-a|-B|-b|-c|-D|-d|-e|-F|-f|-H|-h|-I|-i|-L|-l|-O|-o|-v|-X|-x)
	    OPTS="${OPTS} $1"; shift ;;
	--) shift; break ;;
	*)
	    if test -n "${INPUT_CMD}"; then
		INPUT_FILE="";
	    else
		INPUT_FILE=$1
	    fi;
	    shift ;;
    esac
done

if test -n "${INPUT_CMD}"; then
    ${INPUT_CMD} if=$@ 2>/dev/null | ${REAL_OD} ${OPTS}
else
    ${REAL_OD} ${OPTS} $@
fi
